# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [105]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([2,1,4])
a1
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[4,5,8,]])
a2
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3,
                4,5,6,
                7,8,9]],
              [[10,11,12,
               13,14,15,
               16,17,18]]])
a3.shape

(2, 1, 9)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [23]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.shape, a1.dtype, a1.size

(1, (3,), dtype('int32'), 3)

In [24]:
# Attributes of 2-dimensional array
a2.ndim, a2.shape, a2.dtype, a2.size

(2, (1, 4), dtype('int32'), 4)

In [25]:
# Attributes of 3-dimensional array
a3.ndim, a3.shape, a3.dtype, a3.size

(3, (2, 1, 9), dtype('int32'), 18)

In [31]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 

df = pd.DataFrame(a2)
df

0  1  2  3
0  4  5  8  6

In [33]:
# Create an array of shape (10, 2) with only ones
Ones = np.ones((10,2))
Ones


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
# Create an array of shape (7, 2, 3) of only zeros
Zeros = np.zeros((7,2,3))
Zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [39]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,10, size=(7,2))
random_array

array([[5, 3],
       [4, 9],
       [7, 0],
       [5, 8],
       [2, 0],
       [0, 4],
       [3, 7]])

In [41]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_array = np.random.random((3,5))
float_array

array([[0.83731625, 0.481154  , 0.46311197, 0.298294  , 0.78101071],
       [0.83120793, 0.88232008, 0.08818932, 0.82439475, 0.61966938],
       [0.93199602, 0.96399584, 0.04292353, 0.35213285, 0.16930711]])

In [43]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [45]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a5 = np.random.randint(1,10, size=(3,7))
a5
# Find the unique numbers in the array you just created
np.unique(a5)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# Find the 0'th index of the latest array you created
a3[0]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[5, 3],
       [4, 9]])

In [53]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2,:2]

array([[5, 3],
       [4, 9]])

In [62]:
# Create a random array of numbers between 0 & 10 and an array of ones
a6= np.random.randint(10, size=(3,5))
a6
# both of size (3, 5), save them both to variables
ones = np.ones((3, 5))

In [69]:
# Add the two arrays together
a1.shape, a2.shape

((3,), (1, 4))

In [70]:
# Create another array of ones of shape (5, 3)
array_ones = np.ones((5,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
# Try add the array of ones and the other most recent array together
(a1+array_ones)

array([[3., 2., 5.],
       [3., 2., 5.],
       [3., 2., 5.],
       [3., 2., 5.],
       [3., 2., 5.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [76]:
# Create another array of ones of shape (3, 5)
new_ones_array = np.ones((3,5))
new_ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
# Subtract the new array of ones from the other most recent array
a1 - a2


array([[-2, -4, -4]])

In [86]:
# Multiply the ones array with the latest array
array_ones * a2

array([[4., 5., 8.],
       [4., 5., 8.],
       [4., 5., 8.],
       [4., 5., 8.],
       [4., 5., 8.]])

In [88]:
# Take the latest array to the power of 2 using '**'
a2 ** 2

array([[16, 25, 64]], dtype=int32)

In [89]:
# Do the same thing with np.square(a2)
np.square(a2)

array([[16, 25, 64]], dtype=int32)

In [90]:
# Find the mean of the latest array using np.mean()
np.mean(a2)

5.666666666666667

In [91]:
# Find the maximum of the latest array using np.max()
np.max(a2)

8

In [93]:
# Find the minimum of the latest array using np.min()
np.min(a3)

1

In [94]:
# Find the standard deviation of the latest array
np.std(a2)

1.699673171197595

In [96]:
# Find the variance of the latest array
np.var(a3)

26.916666666666668

In [98]:
# Reshape the latest array to (3, 5, 1)
a2.shape, a3.shape

((1, 3), (2, 1, 9))

In [109]:
a2_reshape= a2.reshape(1,3,1)

a2_reshape

array([[[4],
        [5],
        [8]]])

In [110]:
a2_reshape * a3

array([[[  4,   8,  12,  16,  20,  24,  28,  32,  36],
        [  5,  10,  15,  20,  25,  30,  35,  40,  45],
        [  8,  16,  24,  32,  40,  48,  56,  64,  72]],

       [[ 40,  44,  48,  52,  56,  60,  64,  68,  72],
        [ 50,  55,  60,  65,  70,  75,  80,  85,  90],
        [ 80,  88,  96, 104, 112, 120, 128, 136, 144]]])

In [100]:
# Transpose the latest array
a3.T, a3.T.shape

(array([[[ 1, 10]],
 
        [[ 2, 11]],
 
        [[ 3, 12]],
 
        [[ 4, 13]],
 
        [[ 5, 14]],
 
        [[ 6, 15]],
 
        [[ 7, 16]],
 
        [[ 8, 17]],
 
        [[ 9, 18]]]),
 (9, 1, 2))

What does the transpose do?

In [101]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.randint(0,10, size=(3,3))

array([[8, 3, 8],
       [2, 6, 5],
       [7, 8, 4]])

In [115]:
# Perform a dot product on the two newest arrays you created
np.dot(a2_reshape ,a3)

array([[[[  4,   8,  12,  16,  20,  24,  28,  32,  36],
         [ 40,  44,  48,  52,  56,  60,  64,  68,  72]],

        [[  5,  10,  15,  20,  25,  30,  35,  40,  45],
         [ 50,  55,  60,  65,  70,  75,  80,  85,  90]],

        [[  8,  16,  24,  32,  40,  48,  56,  64,  72],
         [ 80,  88,  96, 104, 112, 120, 128, 136, 144]]]])

In [116]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat1 = np.random.randint(0,10, size=(4,3))

mat2 = np.random.randint(0,10, size=(4,3))

mat1 , mat2

(array([[0, 2, 9],
        [7, 5, 7],
        [8, 3, 0],
        [0, 9, 3]]),
 array([[6, 1, 2],
        [0, 4, 0],
        [7, 0, 0],
        [1, 1, 5]]))

In [118]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1.T, mat2)

array([[56, 28,  0],
       [42, 31, 49],
       [57, 40, 33]])

It doesn't work. How would you fix it?

In [122]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
mat1.T, mat2.T
# a dot product on them both
np.dot(mat1.T, mat2)

array([[56, 28,  0],
       [42, 31, 49],
       [57, 40, 33]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [130]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a7=np.random.randint(0,10, size=(3,5))
a8=np.random.randint(0,10 , size=(3,5))

a7, a8

(array([[5, 6, 9, 6, 9],
        [2, 1, 8, 7, 9],
        [6, 8, 3, 3, 0]]),
 array([[7, 2, 6, 1, 1],
        [6, 5, 2, 8, 9],
        [5, 9, 9, 5, 0]]))

In [131]:
# Compare the two arrays with '>'
a7 > a8

array([[False,  True,  True,  True,  True],
       [False, False,  True, False, False],
       [ True, False, False, False, False]])

What happens when you compare the arrays with `>`?

In [134]:
# Compare the two arrays with '>='
a7 > a2_reshape

array([[[ True,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False, False, False]]])

In [135]:
# Find which elements of the first array are greater than 7
a7 > 7

array([[False, False,  True, False,  True],
       [False, False,  True, False,  True],
       [False,  True, False, False, False]])

In [136]:
# Which parts of each array are equal? (try using '==')
a3 == 3

array([[[False, False,  True, False, False, False, False, False, False]],

       [[False, False, False, False, False, False, False, False, False]]])

In [137]:
# Sort one of the arrays you just created in ascending order
np.sort(a3)

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18]]])

In [139]:
# Sort the indexes of one of the arrays you just created
np.argsort(a7)

array([[0, 1, 3, 2, 4],
       [1, 0, 3, 2, 4],
       [4, 2, 3, 0, 1]], dtype=int64)

In [140]:
# Find the index with the maximum value in one of the arrays you've created
np.max(a7)

9

In [141]:
# Find the index with the minimum value in one of the arrays you've created
np.min(a7)

0

In [143]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argsort(a7, axis=1)

array([[0, 1, 3, 2, 4],
       [1, 0, 3, 2, 4],
       [4, 2, 3, 0, 1]], dtype=int64)

In [144]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argsort(a7, axis=0)

array([[1, 1, 2, 2, 2],
       [0, 0, 1, 0, 0],
       [2, 2, 0, 1, 1]], dtype=int64)

In [147]:
# Create an array of normally distributed random numbers
np.random.randn(10)

array([-0.89312027, -0.33481725,  1.56038014,  0.128551  ,  0.54957635,
       -1.27087181,  2.38903596,  1.84341376,  1.36343549,  0.82876598])

In [148]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])